config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  
  resources :users, except: [:destroy, :index]
  
  resources :teacher_student_links, only: [:create, :destroy]
  
  resources :courses, except: [:index, :new] do
    resources :course_students, only: :create
  end
  
  resources :course_students, only: [:create, :destroy]
  
  resources :assignments do
    resources :course_assignments, only: :create
    resources :student_assignment_links, only: :create
    member do
      get 'set_as_current_assignment', as: 'set_current'
    end
  end
  
  resources :problems, except: :destroy do
    resources :assignment_problems, only: :create
  end
  
  resources :student_assignment_links, only: :destroy
  
  resources :assignment_problems, only: :destroy
  
  resources :course_assignments, only: :destroy
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  validates :teacher, :title, presence: true
  
  belongs_to :teacher,
    class_name: "User",
    foreign_key: :teacher_id,
    inverse_of: :created_assignments
    
  has_many :links_with_students,
    class_name: "StudentAssignmentLink",
    foreign_key: :assignment_id,
    inverse_of: :assignment,
    dependent: :destroy
    
  has_many :students, through: :links_with_students, source: :student
  
  has_many :links_with_problems,
    class_name: "AssignmentProblem",
    foreign_key: :assignment_id,
    inverse_of: :assignment,
    dependent: :destroy
  
  has_many :problems, through: :links_with_problems, source: :problem
  
  has_many :links_with_courses,
    class_name: "CourseAssignment",
    foreign_key: :assignment_id,
    inverse_of: :assignment,
    dependent: :destroy
  
  has_many :courses, through: :links_with_courses, source: :course
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_filter :require_creator, only: [:edit, :update, :destroy]
  before_filter :require_teacher, only: [:index, :new, :create]
  before_filter :require_logged_in, only: :show
  
  def index
    @assignments = current_user.created_assignments
    
    render :index
  end
  
  def show
    @assignment = Assignment.find(params[:id])
    @problems = @assignment.problems
    
    unless current_user.user_type == "Student"
      @unassigned_courses = current_user.select_unassigned_courses(@assignment)
      @unassigned_students = current_user.select_unassigned_students(@assignment)
    end
    
    render :show
  end
  
  def new
    @assignment = Assignment.new
    
    render :new
  end
  
  def create
    @assignment = current_user.created_assignments.new(assignment_params)
    
    if @assignment.save
      set_current_assignment(@assignment)
      redirect_to assignment_url(@assignment)
    else
      flash.now[:errors] = @assignment.errors.full_messages
      render :new
    end
  end
  
  def edit
    @assignment = Assignment.find(params[:id])
    
    render :edit
  end
  
  def update
    @assignment = Assignment.find(params[:id])
    
    if @assignment.update(assignment_params)
      set_current_assignment(@assignment)
      redirect_to assignment_url(@assignment)
    else
      flash.now[:errors] = @assignment.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    assignment = Assignment.find(params[:id])
    
    clear_current_assignment if current_assignment == assignment
    
    assignment.destroy
    redirect_to user_url(current_user)
  end
  
  def set_as_current_assignment
    assignment = Assignment.find(params[:id])
    
    set_current_assignment(assignment)
    
    redirect_to assignment_url(assignment)
  end
  
  private
  def assignment_params
    params.require(:assignment).permit(:title, :description, :due_date)
  end
  
  def require_creator
    assignment = Assignment.find(params[:id])
    unless assignment.teacher_id == current_user.id
      flash[:errors] = ["Can't edit someone else's assignment."]
      redirect_to user_url(current_user)
    end
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<% action = assignment.persisted? ? assignment_url(assignment) : assignments_url %>
<% button_text = assignment.persisted? ? "Save" : "Create Assignment" %>

<form action="<%= action %>" method="POST">
	<%= authenticity_token %>
	
	<% if assignment.persisted? %>
		<input type="hidden" name="_method" value="PUT">
	<% end %>
	
	<label for="assignment_title">Title</label>
	<input type="text" name="assignment[title]" id="assignment_title" value="<%= assignment.title %>">
	
	<label for="assignment_description">Description</label>
	<textarea name="assignment[description]" id="assignment_description"><%= assignment.description %></textarea>
	
	<label for="assignment_due_date">Due Date</label>
	<input type="date" name="assignment[due_date]" id="assignment_due_date" value="<%= assignment.due_date %>">
	
	<button><%= button_text %></button>
</form>

app/views/assignments/edit.html.erb
<h1>Edit Assignment</h1>

<%= render "form", assignment: @assignment %>

app/views/assignments/index.html.erb
<h1>Your Assignments</h1>

<% unless @assignments.empty? %>
	<ul>
		<% @assignments.each do |assignment| %>
			<li>
				<a href="<%= assignment_url(assignment) %>"><%= assignment.title %></a>
				<%= link_to "Edit", edit_assignment_url(assignment) %>
				<%= button_to "Delete", assignment_url(assignment), method: :delete %>
			</li>
		<% end %>
	</ul>
<% end %>

<%= link_to "Create a New Assignment", new_assignment_url %>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>

<%= render "form", assignment: @assignment %>

<p><a href="<%= problems_url %>">Browse problems</a> to add</p>

app/views/assignments/show.html.erb
<h1><%= @assignment.title %></h1>
<p><%= @assignment.description %></p>
<% if @assignment.due_date %>
	<h4>Due: <%= @assignment.due_date %></h4>
<% end %>

<% type = current_user.user_type %>
<% unless type == "Student" %>
	<%= link_to "Edit Assignment", edit_assignment_url(@assignment) %>
	<%= link_to "Set as Current Assignment", set_current_assignment_url(@assignment) %>

	<h2>Assign this Problem Set...</h2>
	
	<form action="<%= assignment_course_assignments_url(@assignment) %>">
		<%= authenticity_token %>
		
		<label for="course_id">...to a Course:</label>
		<select name="course_id" id="course_id">
			<option "selected">--SELECT--</option>
			<% @unassigned_courses.each do |course| %>
				<option value="<%= course.id %>"><%= course.title %></option>
			<% end %>
		</select>
		
		<button>Assign to Course</button>
	</form>
		
	<form action="<%= assignment_student_assignment_links_url(@assignment) %>">
		<%= authenticity_token %>
	
		<label for="student_id">...to a Student:</label>
		<select name="student_id" id="student_id">
			<option "selected">--SELECT--</option>
			<% @unassigned_students.each do |student| %>
				<option value="<%= student.id %>"><%= student.name %></option>
			<% end %>
		</select>
	
		<button>Assign to Student</button>
	</form>
<% end %>

<% unless @problems.empty? %>
	<ul>
		<% @problems.each do |problem| %>
			<li>
				<% if type == "Student" %>
					<h3><%= problem.title %></h3>
				<% else %>
					<h3><a href="<%= problem_url(problem) %>"><%= problem.title %></a></h3>
				<% end %>
				
				<p><%= problem.body %></p>
			</li>
		<% end %>
	</ul>
<% end %>

<% unless type == "Student" %>
	<p><a href="<%= problems_url %>">Browse problems</a> to add more</p>
<% end %>