config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  
  resources :users, except: [:destroy, :index]
  
  resources :teacher_student_links, only: [:create, :destroy]
  
  resources :courses, except: [:index, :new] do
    resources :course_students, only: :create
  end
  
  resources :course_students, only: [:create, :destroy]
  
  resources :assignments do
    resources :course_assignments, only: :create
    resources :student_assignment_links, only: :create
    member do
      get 'set_as_current_assignment', as: 'set_current'
    end
  end
  
  resources :problems, except: :destroy do
    resources :assignment_problems, only: :create
  end
  
  resources :student_assignment_links, only: :destroy
  
  resources :assignment_problems, only: :destroy
  
  resources :course_assignments, only: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :email, :user_type, :password_digest, presence: true
  validates :email, uniqueness: true
  validates :user_type, inclusion: { in: ["Student", "Teacher", "Admin"] }
  validates :password, length: { minimum: 8, allow_nil: true }
  
  attr_reader :password
  
  has_many :sessions, inverse_of: :user, dependent: :destroy
  
  has_many :links_with_students,
    class_name: "TeacherStudentLink",
    foreign_key: :teacher_id,
    inverse_of: :teacher,
    dependent: :destroy
    
  has_many :links_with_teachers,
    class_name: "TeacherStudentLink",
    foreign_key: :student_id,
    inverse_of: :student,
    dependent: :destroy
    
  has_many :students, through: :links_with_students, source: :student
  
  has_many :teachers, through: :links_with_teachers, source: :teacher
  
  has_many :taught_courses,
     class_name: "Course",
     foreign_key: :teacher_id,
     inverse_of: :teacher,
     dependent: :destroy
     
  has_many :links_with_taken_courses,
    class_name: "CourseStudents",
    foreign_key: :student_id,
    inverse_of: :student,
    dependent: :destroy
    
  has_many :taken_courses, through: :links_with_taken_courses, source: :course
  
  has_many :created_assignments,
    class_name: "Assignment",
    foreign_key: :teacher_id,
    inverse_of: :teacher,
    dependent: :destroy
    
  has_many :links_with_assigned_assignments,
    class_name: "StudentAssignmentLink",
    foreign_key: :student_id,
    inverse_of: :student,
    dependent: :destroy
    
  has_many :assigned_assignments, through: :links_with_assigned_assignments, source: :assignment
  
  has_many :created_problems,
    class_name: "Problem",
    foreign_key: :creator_id,
    inverse_of: :creator
  
  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    return nil if user.nil?
    
    return user if user.is_password?(password)
    
    nil
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def reset_session_token!
    session = self.sessions.create!
    session.token
  end
  
  def sort_students_by_course
    courses = self.taught_courses.includes(:students)
    students = self.students
    course_hash = Hash.new { [] }
    seen = Hash.new { false }
    
    courses.each do |course|
      course.students.includes(:links_with_teachers).each do |student|
        course_hash[course] += [student]
        seen[student] = true
      end
    end
    
    students.each do |student|
      next if seen[student]
      course_hash["None"] += [student]
    end
    
    course_hash
  end
  
  def sort_courses
    courses = self.taught_courses.to_a
    courses.sort! { |x, y| x.title <=> y.title }
    courses = ["None"] + courses
  end
  
  def select_out_of_course_students(course_students)
    in_course = Hash.new { false }
    course_students.each do |student|
      in_course[student] = true
    end
    
    self.students.select { |student| !in_course[student] }
  end
  
  def select_unassigned_courses(assignment)
    already_assigned = Hash.new { false }
    assignment.courses.each do |course|
      already_assigned[course] = true
    end
    
    self.taught_courses.select { |course| !already_assigned[course] }
  end
  
  def select_unassigned_students(assignment)
    already_assigned = Hash.new { false }
    assignment.students.each do |student|
      already_assigned[student] = true
    end
    
    self.students.select { |student| !already_assigned[student] }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_same_user, only: [:show, :edit, :update]
  before_filter :require_logged_out, only: [:new, :create]
  
  def show
    @user = User.find(params[:id])
    
    if @user.user_type == "Teacher"
      @course_students = @user.sort_students_by_course
      @ordered_courses = @user.sort_courses
      @course = Course.new
    elsif @user.user_type == "Student"
      @courses = @user.taken_courses.includes(:teacher)
    end
    
    render :show
  end
  
  def new
    @user = User.new
    
    render :new
  end
  
  def create
    @user = User.new(user_params)
    
    unless params[:user][:password] == params[:password_confirm]
      flash.now[:errors] = ["Passwords do not match"]
      render :new
      return
    end
    
    unless ["Student", "Teacher"].include?(params[:user][:user_type])
      flash.now[:errors] = ["Choose an account type."]
      render :new
      return
    end
    
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
    
    render :edit
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :user_type)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_student.html.erb
<h1>Courses</h1>

<form action="<%= course_students_url %>" method="POST">
	<%= authenticity_token %>
	<label for="course_students_course_code">Enter Course Code here:</label>
	<input type="text" id="course_students_course_code" name="course_code">
	<button>Join Course</button>
</form>

<ul>
	<% courses.each do |course| %>
		<li><%= course.title %></li>
	<% end %>
</ul>

app/views/users/_teacher.html.erb
<% count = 0 %>

<h1>Students</h1>

<% ordered_courses.each do |course| %>
	<div class="course">
		<% unless course == "None" %>
			<h3><a href="<%= course_url(course) %>"><%= course.title %></a></h3>
			<form action="<%= course_url(course) %>" method="POST">
				<%= authenticity_token %>
				<input type="hidden" name="_method" value="DELETE">
				<button>Delete</button>
			</form>
		<% end %>
		
		<ul>
			<% course_students[course].each do |student| %>
				<% count += 1 %>
				<li>
					<h5><%= student.name %></h5>
					<p><%= student.email %></p>
					<% link = student.links_with_teachers.select { |link| link.teacher_id == current_user.id }.first %>
					<%= button_to "Remove Student", teacher_student_link_url(link), method: :delete %>
				</li>
			<% end %>
		</ul>
	</div>
<% end %>

<% if count == 0 %>
	<p> You have no students. </p>
<% end %>

<%= link_to "Create New Assignment", new_assignment_url %>
<%= link_to "All Assignments", assignments_url %>

<div class="new_student">
	<form action="<%= teacher_student_links_url %>" method="POST">
		<%= authenticity_token %>
		<h1>Add a Student</h1>
		<label for="student_email">Enter student email:</label>
		<input type="text" name="student_email" id="student_email">
		<button>Add Student</button>
	</form>
</div>

<div class="new_course">
	<h1>Add a New Course</h1>
	<%= render "courses/form", course: @course %>
</div>

app/views/users/edit.html.erb
<h1>Edit My Info</h1>

<form action="<%= user_url(@user) %>" method="POST">
	<input type="hidden" name="_method" value="PATCH">
	
	<%= authenticity_token %>
	
	<label for="user_name">Name</label>
	<input type="text" id="user_name" name="user[name]" value="<%= @user.name %>">
	
	<label for="user_email">Email</label>
	<input type="email" id="user_email" name="user[email]" value="<%= @user.email %>">
	
	<button>Update</button>
	<%= link_to "Cancel", user_url(@user) %>
</form>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST">
	<%= authenticity_token %>
	
	<input type="radio" 
				name="user[user_type]" 
				id="user_type_student" 
				value="Student" 
				<%= @user.user_type == "Student" ? "checked" : "" %>>
	<label for="user_type_student">Student</label>
	
	<input type="radio" 
				name="user[user_type]" 
				id="user_type_teacher" 
				value="Teacher"
				<%= @user.user_type == "Teacher" ? "checked" : "" %>>
	<label for="user_type_teacher">Teacher</label>
	
	<label for="user_name">First and Last Name</label>
	<input type="text" id="user_name" name="user[name]" value="<%= @user.name %>">
	
	<label for="user_email">Email</label>
	<input type="email" id="user_email" name="user[email]" value="<%= @user.email %>">
	
	<label for="user_password">Password</label>
	<input type="password" id="user_password" name="user[password]">
	
	<label for="password_confirm">Confirm Password</label>
	<input type="password" id="password_confirm" name="password_confirm">
	
	<button>Sign Up</button>
</form>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<%= link_to "Edit My Info", edit_user_url(@user) %>

<% if @user.user_type == "Teacher" %>
	<%= render "teacher", ordered_courses: @ordered_courses, course_students: @course_students %>
<% elsif @user.user_type == "Student" %>
	<%= render "student", courses: @courses %>
<% end %>