config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  
  resources :users, except: [:destroy, :index]
  
  resources :teacher_student_links, only: [:create, :destroy]
  
  resources :courses, except: [:index, :new] do
    resources :course_students, only: :create
  end
  
  resources :course_students, only: [:create, :destroy]
  
  resources :assignments do
    resources :course_assignments, only: :create
    resources :student_assignment_links, only: :create
    member do
      get 'set_as_current_assignment', as: 'set_current'
    end
  end
  
  resources :problems, except: :destroy do
    resources :assignment_problems, only: :create
  end
  
  resources :student_assignment_links, only: :destroy
  
  resources :assignment_problems, only: :destroy
  
  resources :course_assignments, only: :destroy
end

app/views/shared/_header.html.erb
<nav class="header">
	<% if logged_in? %>
		Logged in as 
		<a href="<%= user_url(current_user) %>"><%= current_user.name %></a>
		<%= button_to "Log Out", session_url, method: :delete %>
	<% else %>
		<%= link_to "Log In", new_session_url %>
		<%= link_to "Sign Up", new_user_url %>
	<% end %>
	
	<% unless current_assignment.nil? %>
		<p>Current Assignment: <a href="<%= assignment_url(current_assignment) %>"><%= current_assignment.title %></a></p>
	<% end %>
</nav>

app/views/shared/_notices.html.erb
<% if flash[:errors] %>
	<ul class="errors">
		<% flash[:errors].each do |error| %>
			<li><%= error %></li>
		<% end %>
	</ul>
<% end %>

<% if flash[:notices] %>
	<ul class="notices">
		<% flash[:notices].each do |notice| %>
			<li><%= notice %></li>
		<% end %>
	</ul>
<% end %>