config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  
  resources :users, except: [:destroy, :index]
  
  resources :teacher_student_links, only: [:create, :destroy]
  
  resources :courses, except: [:index, :new] do
    resources :course_students, only: :create
  end
  
  resources :course_students, only: [:create, :destroy]
  
  resources :assignments do
    resources :course_assignments, only: :create
    resources :student_assignment_links, only: :create
    member do
      get 'set_as_current_assignment', as: 'set_current'
    end
  end
  
  resources :problems, except: :destroy do
    resources :assignment_problems, only: :create
  end
  
  resources :student_assignment_links, only: :destroy
  
  resources :assignment_problems, only: :destroy
  
  resources :course_assignments, only: :destroy
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :require_logged_in, only: :create
  before_filter :require_involved_in_course, only: :show
  before_filter :require_course_creator, except: [:create, :show]
  
  def show
    @course = Course.find(params[:id])
    @assignments = @course.assignments
    unless current_user.user_type == "Student"
      @students = @course.students
      @teacher_students = current_user.select_out_of_course_students(@students)
    end
    
    render :show
  end
  
  def create
    @course = current_user.taught_courses.new(course_params)
    
    if @course.save
      redirect_to course_url(@course)
    else
      flash[:errors] = @course.errors.full_messages
      redirect_to user_url(current_user)
    end
  end
  
  def edit
    @course = Course.find(params[:id])
    
    render :edit
  end
  
  def update
    @course = Course.find(params[:id])
    
    if @course.update(course_params)
      redirect_to course_url(@course)
    else
      flash.now[:errors] = @course.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    Course.find(params[:id]).destroy
    redirect_to user_url(current_user)
  end
  
  private
  def course_params
    params.require(:course).permit(:title, :description)
  end
  
  def require_involved_in_course
    course = Course.find(params[:id])
    
    if current_user.user_type == "Teacher"
      unless course.teacher_id == current_user.id
        flash[:errors] = ["Must be involved in the course to view it"]
        redirect_to user_url(current_user) 
      end
    elsif current_user.user_type == "Student"
      students = course.students.to_a
      
      unless students.include?(current_user)
        flash[:errors] = ["Must be involved in the course to view it"]
        redirect_to user_url(current_user) 
      end
    end
  end
  
  def require_course_creator
    course = Course.find(params[:id])
    unless course.teacher_id == current_user.id
      flash[:errors] = ["Must be the creator of the course"]
      redirect_to user_url(current_user)
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<% action = course.persisted? ? course_url(course) : courses_url %>
<% button_text = course.persisted? ? "Save" : "Create Course" %>

<form action="<%= action %>" method="POST">
	<%= authenticity_token %>
	<% if course.persisted? %>
		<input type="hidden" name="_method" value="PATCH">
	<% end %>
	
	<label for="course_title">Title</label>
	<input type="text" id="course_title" name="course[title]" value="<%= course.title %>">
	
	<label for="course_description">Description</label>
	<textarea id="course_description" name="course[description]"><%= course.description %></textarea>
		
	<button><%= button_text %></button>
</form>

app/views/courses/edit.html.erb
<h1>Edit Course</h1>
<%= render "form", course: @course %>

app/views/courses/show.html.erb
<h1><%= @course.title %></h1>
<p><%= @course.description %></p>

<% unless current_user.user_type == "Student" %>

	<%= link_to "Edit", edit_course_url(@course) %>
	
	<form action="<%= course_url(@course) %>" method="POST">
		<%= authenticity_token %>
		<input type="hidden" name="_method" value="DELETE">
		<button>Delete</button>
	</form>

	<p>Course Code: <%= @course.course_code %></p>
	
	<h2>Students</h2>
	<ul>
		<% @students.each do |student| %>
			<li><%= student.name %></li>
		<% end %>
	</ul>
	
	<% unless @teacher_students.empty? %>
		<form action="<%= course_course_students_url(@course) %>" method="POST">
			<%= authenticity_token %>
		
			<h3>Add Students</h3>
		
			<label for="student_id">Choose:</label>
			<select name="student_id" id="student_id">
				<option "selected">--SELECT--</option>
				<% @teacher_students.each do |student| %>
					<option value="<%= student.id %>"><%= student.name %></option>
				<% end %>
			</select>
		
			<button>Add</button>
		</form>
	<% end %>
<% end %>

<h2>Assignments</h2>

<% if @assignments.length > 0 %>
	<ul>
		<% @assignments.each do |assignment| %>
			<li>
				<a href=<%= assignment_url(assignment) %>><%= assignment.title %></a>
				Created on: <%= assignment.created_at.to_date %>
				<% link = CourseAssignment.where("course_id = ? AND assignment_id = ?", @course.id, assignment.id) %>
				<% unless current_user.user_type == "Student" %>
					<%= button_to "Remove", course_assignment_url(link), method: :delete %>
				<% end %>
			</li>
		<% end %>
	</ul>
<% else %>
	<p>There are no assignments for this course.</p>
<% end %>